//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.PawnLoans = new HashSet<PawnLoans>();
            this.PurchaseContracts = new HashSet<PurchaseContracts>();
        }
    
        public int client_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string document_type { get; set; }
        public string document_number { get; set; }
        public string pesel { get; set; }
        public string address { get; set; }
        public string address_source { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PawnLoans> PawnLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseContracts> PurchaseContracts { get; set; }
    }
}
