//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestRates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterestRates()
        {
            this.PawnLoans = new HashSet<PawnLoans>();
        }
    
        public int interest_rate_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> rate_percent { get; set; }
        public Nullable<int> period_days { get; set; }
        public Nullable<decimal> minimal_interest { get; set; }
        public bool is_default { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PawnLoans> PawnLoans { get; set; }
    }
}
