//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PawnLoanItems
    {
        public int pawn_loan_item_id { get; set; }
        public int pawn_loan_id { get; set; }
        public int item_id { get; set; }
        public decimal loan_amount_for_item { get; set; }
        public string notes { get; set; }
        public int history_id { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        public virtual PawnLoans PawnLoans { get; set; }
    }
}
