//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PawnLoans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PawnLoans()
        {
            this.PawnLoanItems = new HashSet<PawnLoanItems>();
            this.PawnLoans1 = new HashSet<PawnLoans>();
        }
    
        public int pawn_loan_id { get; set; }
        public int client_id { get; set; }
        public string agreement_number { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime due_date { get; set; }
        public decimal total_loan_amount { get; set; }
        public int interest_rate_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> previous_loan_id { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        public virtual InterestRates InterestRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PawnLoanItems> PawnLoanItems { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PawnLoans> PawnLoans1 { get; set; }
        public virtual PawnLoans PawnLoans2 { get; set; }
    }
}
