//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int price_history_id { get; set; }
        public int item_id { get; set; }
        public Nullable<decimal> previous_value { get; set; }
        public Nullable<decimal> new_value { get; set; }
        public int changed_by { get; set; }
        public System.DateTime changed_at { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Items Items { get; set; }
    }
}
