//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseContracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseContracts()
        {
            this.PurchaseContractItems = new HashSet<PurchaseContractItems>();
        }
    
        public int purchase_contract_id { get; set; }
        public int client_id { get; set; }
        public string agreement_number { get; set; }
        public System.DateTime purchase_date { get; set; }
        public decimal total_purchase_price { get; set; }
        public int status_id { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ContractStatuses ContractStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseContractItems> PurchaseContractItems { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
    }
}
