//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.SalesItems = new HashSet<SalesItems>();
        }
    
        public int sale_id { get; set; }
        public decimal sale_price { get; set; }
        public System.DateTime sale_date { get; set; }
        public int finalization_source_id { get; set; }
        public Nullable<int> online_offer_id { get; set; }
        public int payment_id { get; set; }
        public int status_id { get; set; }
        public bool is_active { get; set; }
        public int history_id { get; set; }
    
        public virtual FinalizationSources FinalizationSources { get; set; }
        public virtual OnlineSaleOffers OnlineSaleOffers { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual RecordHistory RecordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesItems> SalesItems { get; set; }
        public virtual SalesStatuses SalesStatuses { get; set; }
    }
}
